pandas는 Python에서 데이터를 쉽고 효율적으로 분석하고 처리하기 위해 사용하는 대표적인 데이터 분석 라이브러리입니다. 엑셀과 비슷한 형태의 표(Tabular Data)를 다룰 수 있으며, Series와 DataFrame이라는 강력한 자료구조를 제공합니다. CSV, Excel, SQL 등의 다양한 데이터 파일을 불러와 정렬, 필터링, 그룹화, 결측치 처리, 통계 분석 등을 간편하게 수행할 수 있으며, 대량의 데이터를 빠르게 가공할 수 있습니다.

```
# 설치
pip install pandas
# 또는
python -m pip install pandas
```

In [2]:
import pandas as pd

In [3]:
# pandas 버전 확인하기
pd.__version__

'3.0.3'

***
# **1. Series**
Series는 Pandas에서 사용하는 가장 기본적인 1차원 데이터 구조로, 값(Value)과 인덱스(Index)가 함께 구성된 자료형입니다. NumPy의 1차원 배열과 비슷하지만, 각 데이터에 이름표 역할을 하는 인덱스가 추가되어 데이터를 더 체계적으로 관리할 수 있습니다.

<img src = "./images/시리즈.png" width = 200>

In [4]:
idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
data = [67, 75, 90, 62, 98]

# pd.Series(데이터, 인덱스, ...)
pd.Series(data)

0    67
1    75
2    90
3    62
4    98
dtype: int64

In [5]:
ser1 = pd.Series(data, idx)
print(ser1)
print(ser1.index)           # Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
print(ser1.values)          # [67 75 90 62 98]
print(type(ser1.values))    # <class 'numpy.ndarray'>

# index와 value의 합으로 이루어진 Series
# index는 index 객체
# values는 ndarray

김사과    67
반하나    75
오렌지    90
이메론    62
배애리    98
dtype: int64
Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
[67 75 90 62 98]
<class 'numpy.ndarray'>

### Index 객체란
Index 객체는 Series와 DataFrame에서 각 데이터의 위치를 식별하고 관리하기 위한 “이름표(Label)” 역할을 하는 자료구조입니다. 일반 리스트처럼 보이지만 단순한 데이터 저장용이 아니라, 데이터를 빠르게 검색하고 정렬하며 서로 다른 데이터끼리 매칭할 수 있도록 최적화된 Pandas 전용 객체입니다.

<img src = "./images/인덱스.png" width = 600>

***
# **2. DataFrame**
데이터프레임(DataFrame)은 판다스(Pandas) 라이브러리에서 제공하는 중요하고 강력한 데이터 구조로, 2차원의 테이블 형태 데이터를 다루는 데 사용됩니다. 또한 각 요소는 인덱스(index), 열(column), 값(value)으로 구성되어 있습니다. 데이터프레임은 행과 열로 이루어져 있으며, 각 열은 다양한 데이터 타입을 가질 수 있습니다. 값은 넘파이의 ndarray 기반으로 저장됩니다.

> index와 column 둘 다 index 객체로 이루어져 있음<br>
> 공통 인덱스를 가진 모임<br>
> dataframe은 series의 모임

<img src = "./images/데이터프레임.png" width = 500>

In [6]:
data = [[67, 93, 91],
        [75, 68, 96],
        [87, 81, 82],
        [62, 70, 75],
        [98, 56, 87]]

idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
col = ['국어', '영어', '수학']

# pd.DataFrame(데이터, 인덱스, 컬럼, ...)
pd.DataFrame(data)

    0   1   2
0  67  93  91
1  75  68  96
2  87  81  82
3  62  70  75
4  98  56  87

In [ ]:
pd.DataFrame(data, idx)

      0   1   2
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [ ]:
pd.DataFrame(data, idx, col)

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [ ]:
df = pd.DataFrame(index=idx, columns=col, data=data)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [ ]:
print(df.index)
print(df.columns)
print(df.values)

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='str')
Index(['국어', '영어', '수학'], dtype='str')
[[67 93 91]
 [75 68 96]
 [87 81 82]
 [62 70 75]
 [98 56 87]]

In [ ]:
# 딕셔너리를 사용하여 데이터프레임을 생성하기
# key는 columns으로
dic = {
    '국어':[67, 75, 76, 62, 98],
    '영어':[93, 68, 81, 70, 56],
    '수학':[91, 96, 82, 75, 87]
}

df = pd.DataFrame(data=dic, index=idx)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  76  81  82
이메론  62  70  75
배애리  98  56  87

***
# **3. CSV 파일 읽어오기**
CSV 파일은 Comma-Separated Values(쉼표로 구분된 값) 파일의 약자로, 데이터를 단순한 텍스트 형식으로 저장하는 데 사용되는 파일 형식입니다.

> CSV 파일이랑 Excel은 같다? False<br>
> CSV 파일은 엑셀에서도 열리고 메모장에서도 열리는 아주 가벼운 파일이다.

In [7]:
df = pd.read_csv("./광고모델_브랜드평판.csv")
df

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [ ]:
type(df)        # pandas.DataFrame

pandas.DataFrame

In [ ]:
# 데이터의 간략 정보 확인 가능 (확인할 것 1⭐)
df.info()

# <class 'pandas.DataFrame'>            dataframe 자료형이야
# RangeIndex: 20 entries, 0 to 19       데이터가 20개 있어
# Data columns (total 7 columns):       column은 7개야
# Non-Null Count : 데이터가 몇 개가 차있는지 / 타입은 str이야 / 혈액형은 2개가 빠졌네
# dtypes: str(7)            str형 7개
# memory usage: 1.2 KB      데이터를 불러오는데 사용한 메모리량

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     str
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: str(7)
memory usage: 1.2 KB

In [ ]:
df.columns
# Index(['이름', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='str')
# Index 객체

Index(['이름', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='str')

In [ ]:
#  각각의 변경이 불가능하여 변경하기위해서는 새로 덮어씌워야 함
new_columns = ['name', 'company', 'gender', 'birthday', 'height', 'blood', 'brand']
df.columns = new_columns
df

   name      company gender    birthday   height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271

In [ ]:
# (확인할 것 2⭐)
# describe(): 통계 정보를 반환
df.describe(include=str)    # 문자열에 대한 통계정보를 보여주세요
# describe() 기본값은 숫자형. 현재 데이터에는 숫자정보가 없기 때문에 그냥 똑같이 나옴

# top : 최빈값이 1개라면 그냥 맨 위의 데이터 출력 (의미 없는 데이터가 되어버림)

       name  company gender    birthday height blood      brand
count    20       20     20          20     20    18         20
unique   20       19      2          20     15     4         20
top     변우석  아티스트컴퍼니      남  1991-10-31  178cm     B  3,762,141
freq      1        2     15           1      3     7          1

<img src = "./images/describe.png" width = 600>

In [ ]:
# 원하는 개수의 데이터 보기
df.head()   # 상위 5개의 row를 출력 (기본값이 5)

  name    company gender    birthday   height blood      brand
0  변우석   바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1  임영웅      물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2  손흥민  로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
3  박지훈   YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
4  유재석        안테나      남  1972-08-14    178cm     B  2,015,312

In [ ]:
df.head(3)  # 상위 3개의 row를 출력

  name    company gender    birthday   height blood      brand
0  변우석   바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1  임영웅      물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2  손흥민  로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512

In [ ]:
df.tail() # 하위 5개의 row를 출력

   name    company gender    birthday height blood    brand
15  박보검     더블랙레이블      남  1993-06-16  182cm     O  451,540
16  엄태구        팀호프      남  1983-11-09  181cm     O  380,064
17  구교환      나무엑터스      남  1982-12-14  182cm     A  371,673
18  지예은  S&A엔터테인먼트      여  1994-07-26  171cm   NaN  370,543
19  전지현     이음해시태그      여  1981-10-30  173cm     B  358,271

In [ ]:
df.tail(2) # 하위 2개의 row를 출력

   name    company gender    birthday height blood    brand
18  지예은  S&A엔터테인먼트      여  1994-07-26  171cm   NaN  370,543
19  전지현     이음해시태그      여  1981-10-30  173cm     B  358,271

***
# **4. 정렬하기**

In [ ]:
# sort_index() : 오름차순 정렬 (기본값)
df.sort_index() # index로 오름차순 정렬: 기본값

   name      company gender    birthday   height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271

In [ ]:
df.sort_index(ascending=False) # index로 내림차순 정렬

   name      company gender    birthday   height blood      brand
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141

In [ ]:
df.sort_values(by='height') # 키로 오름차순 정렬

   name      company gender    birthday   height blood      brand
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141

In [ ]:
df.sort_values(by='height', ascending=False) # 키로 내림차순 정렬
# height에서 c하고 .하고 비교하게 되어 아스키코드값이 c가 더 크기 때문에 182cm가 182.2cm보다 크다는 잘못된 결과가 나오게됨
# 👉 문자열 비교는 사전(Dictionary) 순서처럼 비교하기 때문에 "182cm" > "182.2cm" 처럼 이상한 결과가 나올 수 있습니다.

   name      company gender    birthday   height blood      brand
0   변우석     바로엔터테인먼트      남  1991-10-31  190.3cm     B  3,762,141
6   이정후  샌프란시스코 자이언츠      남  1998-08-20    185cm     A  1,015,456
11   공유      매니지먼트 숲      남  1979-07-10    184cm     A    561,519
2   손흥민    로스앤젤레스 FC      남  1992-07-08    183cm    AB  3,067,512
14  김도영     KIA 타이거즈      남  2003-10-02    183cm   NaN    481,761
17  구교환        나무엑터스      남  1982-12-14    182cm     A    371,673
15  박보검       더블랙레이블      남  1993-06-16    182cm     O    451,540
1   임영웅        물고기뮤직      남  1991-06-16  182.2cm     A  3,349,309
16  엄태구          팀호프      남  1983-11-09    181cm     O    380,064
9   이정재      아티스트컴퍼니      남  1972-12-15    180cm     B    664,985
12  이준호    JYP엔터테인먼트      남  1990-01-25    178cm     A    543,485
10  마동석    빅펀치엔터테인먼트      남  1971-03-01    178cm     O    651,035
4   유재석          안테나      남  1972-08-14    178cm     B  2,015,312
13  이찬원     티엔엔터테인먼트      남  1996-11-01    176cm     B    486,700
3   박지훈     YY엔터테인먼트      남  1999-05-29    173cm    AB  2,831,201
19  전지현       이음해시태그      여  1981-10-30    173cm     B    358,271
18  지예은    S&A엔터테인먼트      여  1994-07-26    171cm   NaN    370,543
5   김연아        올댓스포츠      여  1990-09-05    164cm     O  1,085,281
7   고윤정          MAA      여  1996-04-22    163cm     B    855,724
8   김혜윤      아티스트컴퍼니      여  1996-11-10    160cm     B    831,169

In [ ]:
# df의 column이 height인 데이터를 str형변환 후 cm를 ''로 바꾼 후, 숫자(실수형)로 변환
# -> 체이닝 (함수형 프로그래밍)
df['height'] = df['height'].str.replace('cm', '').astype(float)
df
df.info()
# 👉   cm 문자열을 제거한 뒤 숫자(float)로 변환

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     str
 1   company   20 non-null     str
 2   gender    20 non-null     str
 3   birthday  20 non-null     str
 4   height    20 non-null     float64
 5   blood     18 non-null     str
 6   brand     20 non-null     str
dtypes: float64(1), str(6)
memory usage: 1.2 KB

In [ ]:
# 👉 brand 컬럼도 현재 숫자가 아니라 문자열(String) 상태. 쉼표(,)를 제거한 뒤 숫자로 변환
df['brand'] = df['brand'].str.replace(',', '').astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     str
 1   company   20 non-null     str
 2   gender    20 non-null     str
 3   birthday  20 non-null     str
 4   height    20 non-null     float64
 5   blood     18 non-null     str
 6   brand     20 non-null     int64
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [ ]:
# 다시 간단 정보 출력
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     str
 1   company   20 non-null     str
 2   gender    20 non-null     str
 3   birthday  20 non-null     str
 4   height    20 non-null     float64
 5   blood     18 non-null     str
 6   brand     20 non-null     int64
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [ ]:
# 처음과 다르게 숫자형인 것만 출력
df.describe()

           height         brand
count   20.000000  2.000000e+01
mean   177.325000  1.206734e+06
std      7.906751  1.125405e+06
min    160.000000  3.582710e+05
25%    173.000000  4.742058e+05
50%    179.000000  6.580100e+05
75%    182.400000  1.317789e+06
max    190.300000  3.762141e+06

<img src = "./images/describe2.png" width = 600>

In [ ]:
df.sort_values(by='height', ascending=False) # 키로 내림차순 정렬

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
19  전지현       이음해시태그      여  1981-10-30   173.0     B   358271
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10   160.0     B   831169

In [ ]:
# 1차 정렬: 키(내림차순), 2차 정렬: 브랜드(내림차순)
# 정렬 기준이 NaN 값일 때 정렬하면(오름,내림) 맨 아래로 깔리는 것이 기본인데
#  na_position='first'를 주면 NaN을 맨 위로
df.sort_values(by=['height', 'brand'], ascending=[False, False], na_position='first')

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
19  전지현       이음해시태그      여  1981-10-30   173.0     B   358271
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10   160.0     B   831169

***
# **5. 인덱싱**

In [ ]:
df.head()

  name    company gender    birthday  height blood    brand
0  변우석   바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1  임영웅      물고기뮤직      남  1991-06-16   182.2     A  3349309
2  손흥민  로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3  박지훈   YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4  유재석        안테나      남  1972-08-14   178.0     B  2015312

In [ ]:
# column중 blood를 선택해서 출력 (시리즈인 것을 확인할 수 있음)
df['blood']

# 또는
# df.blood

## 둘 다 결과가 같지만 df['blood'] 사용을 권장

0       B
1       A
2      AB
3      AB
4       B
5       O
6       A
7       B
8       B
9       B
10      O
11      A
12      A
13      B
14    NaN
15      O
16      O
17      A
18    NaN
19      B
Name: blood, dtype: str

> 👉 df['blood']는 컬럼명이 어떤 형태든 비교적 안전하게 사용할 수 있습니다.<br>
> 예를 들어 컬럼명이 한글이거나, 공백이 있거나, 특수문자가 있으면 df.blood 방식은 사용할 수 없습니다.

In [ ]:
# blood의 타입 확인하기
type(df['blood'])       # pandas.Series

pandas.Series

In [ ]:
# 위에서 3개 데이터 출력 (방법1)
df.head(3)

  name    company gender    birthday  height blood    brand
0  변우석   바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1  임영웅      물고기뮤직      남  1991-06-16   182.2     A  3349309
2  손흥민  로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512

In [ ]:
# # 위에서 3개 데이터 출력 (방법2)
df[:3]

  name    company gender    birthday  height blood    brand
0  변우석   바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1  임영웅      물고기뮤직      남  1991-06-16   182.2     A  3349309
2  손흥민  로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512

In [ ]:
# loc 인덱싱
df.loc[:, 'name'] # df['name']

# 콤마(,) 기준으로 왼쪽에는 행, 오른쪽은 열
# : 다  'name' name만

0     변우석
1     임영웅
2     손흥민
3     박지훈
4     유재석
5     김연아
6     이정후
7     고윤정
8     김혜윤
9     이정재
10    마동석
11     공유
12    이준호
13    이찬원
14    김도영
15    박보검
16    엄태구
17    구교환
18    지예은
19    전지현
Name: name, dtype: str

> 👉 loc는 DataFrame이나 Series에서 인덱스 이름(Label)과 컬럼명을 기준으로 데이터를 선택하는 인덱서(Indexer)입니다.<br> (인덱스는 숫자일 수도 있고 문자일 수도 있음. 숫자형일 필요는 없지만 unique한 값이어야 함) <br>
> 즉, 숫자 위치가 아니라 실제 행 이름과 열 이름을 사용하여 데이터를 가져옵니다.<br>
> loc는 사람이 읽기 쉽고 데이터 의미를 기준으로 접근하기 때문에 데이터 분석과 전처리 작업에서 가장 많이 사용하는 방식 중 하나입니다.

> df.loc[행에 대한 조건, 열에 대한 조건]

In [ ]:
# 2부터 5까지 행 그리고 name 열들을 가져와
df.loc[2:5, 'name'] # 5번을 포함 (2와 5는 인덱스의 숫자를 그대로 쓰는 것)

2    손흥민
3    박지훈
4    유재석
5    김연아
Name: name, dtype: str

In [ ]:
# 2부터 5까지 행 그리고 name, gender, height 열들을 가져와
df.loc[2:5, ['name', 'gender', 'height']]

  name gender  height
2  손흥민      남   183.0
3  박지훈      남   173.0
4  유재석      남   178.0
5  김연아      여   164.0

In [ ]:
# 2와 5행 그리고 name, gender, height 열들을 가져와
df.loc[[2,5], ['name', 'gender', 'height']]

  name gender  height
2  손흥민      남   183.0
5  김연아      여   164.0

In [ ]:
# 2부터 5까지 행 그리고 'name'부터 'gender'까지 열들을 가져와
df.loc[2:5, 'name':'gender']

  name    company gender
2  손흥민  로스앤젤레스 FC      남
3  박지훈   YY엔터테인먼트      남
4  유재석        안테나      남
5  김연아      올댓스포츠      여

In [ ]:
# iloc 인덱싱: index로 인덱싱
df.iloc[:, 0]

0     변우석
1     임영웅
2     손흥민
3     박지훈
4     유재석
5     김연아
6     이정후
7     고윤정
8     김혜윤
9     이정재
10    마동석
11     공유
12    이준호
13    이찬원
14    김도영
15    박보검
16    엄태구
17    구교환
18    지예은
19    전지현
Name: name, dtype: str

In [ ]:
df.iloc[:, 0:3] # 3을 포함하지 않음

   name      company gender
0   변우석     바로엔터테인먼트      남
1   임영웅        물고기뮤직      남
2   손흥민    로스앤젤레스 FC      남
3   박지훈     YY엔터테인먼트      남
4   유재석          안테나      남
5   김연아        올댓스포츠      여
6   이정후  샌프란시스코 자이언츠      남
7   고윤정          MAA      여
8   김혜윤      아티스트컴퍼니      여
9   이정재      아티스트컴퍼니      남
10  마동석    빅펀치엔터테인먼트      남
11   공유      매니지먼트 숲      남
12  이준호    JYP엔터테인먼트      남
13  이찬원     티엔엔터테인먼트      남
14  김도영     KIA 타이거즈      남
15  박보검       더블랙레이블      남
16  엄태구          팀호프      남
17  구교환        나무엑터스      남
18  지예은    S&A엔터테인먼트      여
19  전지현       이음해시태그      여

> 👉 iloc는 DataFrame이나 Series에서 숫자 위치(Index Position)를 기준으로 데이터를 선택하는 인덱서(Indexer)입니다. 즉, 실제 인덱스 이름이 아니라 행과 열의 순서 번호를 사용하여 데이터를 가져옵니다. iloc는 데이터의 실제 이름과 상관없이 순서 기준으로 접근하기 때문에 반복 처리나 특정 위치 데이터를 다룰 때 많이 사용됩니다.

> 데이터의 위치를 숫자값으로 이용

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     str
 1   company   20 non-null     str
 2   gender    20 non-null     str
 3   birthday  20 non-null     str
 4   height    20 non-null     float64
 5   blood     18 non-null     str
 6   brand     20 non-null     int64
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [ ]:
df.iloc[:, [0, 3]]

   name    birthday
0   변우석  1991-10-31
1   임영웅  1991-06-16
2   손흥민  1992-07-08
3   박지훈  1999-05-29
4   유재석  1972-08-14
5   김연아  1990-09-05
6   이정후  1998-08-20
7   고윤정  1996-04-22
8   김혜윤  1996-11-10
9   이정재  1972-12-15
10  마동석  1971-03-01
11   공유  1979-07-10
12  이준호  1990-01-25
13  이찬원  1996-11-01
14  김도영  2003-10-02
15  박보검  1993-06-16
16  엄태구  1983-11-09
17  구교환  1982-12-14
18  지예은  1994-07-26
19  전지현  1981-10-30

In [ ]:
df.iloc[1:5, 0:2]

  name    company
1  임영웅      물고기뮤직
2  손흥민  로스앤젤레스 FC
3  박지훈   YY엔터테인먼트
4  유재석        안테나

In [ ]:
# height 값들이 180보다 크거나 같은지 알려줘 (True or False로 출력)

df['height'] >= 180

0      True
1      True
2      True
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14     True
15     True
16     True
17     True
18    False
19    False
Name: height, dtype: bool

In [ ]:
# 키가 180 이상인 사람만 출력해줘

df[df['height'] >= 180]

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673

In [ ]:
# 키가 180 이상인 사람 중에서 이름만 출력해줘
df[df['height'] >= 180]['name'] # df['name'][df['height'] >= 180]

0     변우석
1     임영웅
2     손흥민
6     이정후
9     이정재
11     공유
14    김도영
15    박보검
16    엄태구
17    구교환
Name: name, dtype: str

In [ ]:
df['name'][df['height'] >= 180]

0     변우석
1     임영웅
2     손흥민
6     이정후
9     이정재
11     공유
14    김도영
15    박보검
16    엄태구
17    구교환
Name: name, dtype: str

In [ ]:
# 키가 180 이상인 사람 중에서 이름, 성별, 키만 출력해줘
df[df['height'] >= 180][['name', 'gender', 'height']]

   name gender  height
0   변우석      남   190.3
1   임영웅      남   182.2
2   손흥민      남   183.0
6   이정후      남   185.0
9   이정재      남   180.0
11   공유      남   184.0
14  김도영      남   183.0
15  박보검      남   182.0
16  엄태구      남   181.0
17  구교환      남   182.0

In [ ]:
# 키가 180 이상인 사람 중에서 이름, 성별, 키만 출력해줘 (loc 사용)
df.loc[df['height'] >= 180, ['name', 'gender', 'height']]

   name gender  height
0   변우석      남   190.3
1   임영웅      남   182.2
2   손흥민      남   183.0
6   이정후      남   185.0
9   이정재      남   180.0
11   공유      남   184.0
14  김도영      남   183.0
15  박보검      남   182.0
16  엄태구      남   181.0
17  구교환      남   182.0

In [ ]:
blood = ['A', 'B']
df['blood'].isin(blood)

0      True
1      True
2     False
3     False
4      True
5     False
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13     True
14    False
15    False
16    False
17     True
18    False
19     True
Name: blood, dtype: bool

In [ ]:
df[df['blood'].isin(blood)] # df.loc[df['blood'].isin(blood),:]

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10   160.0     B   831169
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
19  전지현       이음해시태그      여  1981-10-30   173.0     B   358271

***
# **6. 결측값**
결측값(Missing Value)은 데이터가 존재하지 않거나 비어있는 값을 의미하며, 보통 NaN(Not a Number) 형태로 표현됩니다. 예를 들어 키, 몸무게, 나이 같은 정보가 입력되지 않았거나 수집 과정에서 누락된 경우 결측값이 발생합니다. 데이터 분석과 머신러닝에서는 결측값이 매우 중요하며, 그대로 두면 평균 계산, 통계 분석, 모델 학습 과정에서 오류나 성능 저하가 발생할 수 있습니다. 결측값 처리는 데이터 품질을 높이고 정확한 분석 결과를 얻기 위한 매우 중요한 데이터 전처리 과정입니다.

> 결측값에 평균, 중앙값 등 대체 값으로 처리

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     str
 1   company   20 non-null     str
 2   gender    20 non-null     str
 3   birthday  20 non-null     str
 4   height    20 non-null     float64
 5   blood     18 non-null     str
 6   brand     20 non-null     int64
dtypes: float64(1), int64(1), str(5)
memory usage: 1.2 KB

In [ ]:
# Nan 값을 가진 데이터 전체를 출력
# null 아닌 값이 False, null 값이 True로 출력
df.isna()

     name  company  gender  birthday  height  blood  brand
0   False    False   False     False   False  False  False
1   False    False   False     False   False  False  False
2   False    False   False     False   False  False  False
3   False    False   False     False   False  False  False
4   False    False   False     False   False  False  False
5   False    False   False     False   False  False  False
6   False    False   False     False   False  False  False
7   False    False   False     False   False  False  False
8   False    False   False     False   False  False  False
9   False    False   False     False   False  False  False
10  False    False   False     False   False  False  False
11  False    False   False     False   False  False  False
12  False    False   False     False   False  False  False
13  False    False   False     False   False  False  False
14  False    False   False     False   False   True  False
15  False    False   False     False   False  False  False
16  False    False   False     False   False  False  False
17  False    False   False     False   False  False  False
18  False    False   False     False   False   True  False
19  False    False   False     False   False  False  False

In [ ]:
df.isnull()

     name  company  gender  birthday  height  blood  brand
0   False    False   False     False   False  False  False
1   False    False   False     False   False  False  False
2   False    False   False     False   False  False  False
3   False    False   False     False   False  False  False
4   False    False   False     False   False  False  False
5   False    False   False     False   False  False  False
6   False    False   False     False   False  False  False
7   False    False   False     False   False  False  False
8   False    False   False     False   False  False  False
9   False    False   False     False   False  False  False
10  False    False   False     False   False  False  False
11  False    False   False     False   False  False  False
12  False    False   False     False   False  False  False
13  False    False   False     False   False  False  False
14  False    False   False     False   False   True  False
15  False    False   False     False   False  False  False
16  False    False   False     False   False  False  False
17  False    False   False     False   False  False  False
18  False    False   False     False   False   True  False
19  False    False   False     False   False  False  False

In [ ]:
# null 아닌 값이 True, null 값이 False로 출력
df.notna()

    name  company  gender  birthday  height  blood  brand
0   True     True    True      True    True   True   True
1   True     True    True      True    True   True   True
2   True     True    True      True    True   True   True
3   True     True    True      True    True   True   True
4   True     True    True      True    True   True   True
5   True     True    True      True    True   True   True
6   True     True    True      True    True   True   True
7   True     True    True      True    True   True   True
8   True     True    True      True    True   True   True
9   True     True    True      True    True   True   True
10  True     True    True      True    True   True   True
11  True     True    True      True    True   True   True
12  True     True    True      True    True   True   True
13  True     True    True      True    True   True   True
14  True     True    True      True    True  False   True
15  True     True    True      True    True   True   True
16  True     True    True      True    True   True   True
17  True     True    True      True    True   True   True
18  True     True    True      True    True  False   True
19  True     True    True      True    True   True   True

In [ ]:
df.notnull()

    name  company  gender  birthday  height  blood  brand
0   True     True    True      True    True   True   True
1   True     True    True      True    True   True   True
2   True     True    True      True    True   True   True
3   True     True    True      True    True   True   True
4   True     True    True      True    True   True   True
5   True     True    True      True    True   True   True
6   True     True    True      True    True   True   True
7   True     True    True      True    True   True   True
8   True     True    True      True    True   True   True
9   True     True    True      True    True   True   True
10  True     True    True      True    True   True   True
11  True     True    True      True    True   True   True
12  True     True    True      True    True   True   True
13  True     True    True      True    True   True   True
14  True     True    True      True    True  False   True
15  True     True    True      True    True   True   True
16  True     True    True      True    True   True   True
17  True     True    True      True    True   True   True
18  True     True    True      True    True  False   True
19  True     True    True      True    True   True   True

In [ ]:
df['height'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: height, dtype: bool

In [ ]:
df[df['height'].isna()]

Empty DataFrame
Columns: [name, company, gender, birthday, height, blood, brand]
Index: []

In [ ]:
import numpy as np

In [ ]:
# df.loc[8, 'height'] = np.nan
# df.loc[19, 'height'] = np.nan

df.loc[[8, 19], 'height'] = np.nan

In [ ]:
df[df['height'].isna()]

   name  company gender    birthday  height blood   brand
8   김혜윤  아티스트컴퍼니      여  1996-11-10     NaN     B  831169
19  전지현   이음해시태그      여  1981-10-30     NaN     B  358271

In [ ]:
df[df['height'].isna()]['name']

8     김혜윤
19    전지현
Name: name, dtype: str

In [ ]:
df[df['height'].notnull()]

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543

In [ ]:
df[~df['height'].isnull()]

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543

In [ ]:
df.loc[df['height'].notnull(), ['name', 'company', 'gender']]
# df[df['height'].notnull()][['name','company','gender']]

   name      company gender
0   변우석     바로엔터테인먼트      남
1   임영웅        물고기뮤직      남
2   손흥민    로스앤젤레스 FC      남
3   박지훈     YY엔터테인먼트      남
4   유재석          안테나      남
5   김연아        올댓스포츠      여
6   이정후  샌프란시스코 자이언츠      남
7   고윤정          MAA      여
9   이정재      아티스트컴퍼니      남
10  마동석    빅펀치엔터테인먼트      남
11   공유      매니지먼트 숲      남
12  이준호    JYP엔터테인먼트      남
13  이찬원     티엔엔터테인먼트      남
14  김도영     KIA 타이거즈      남
15  박보검       더블랙레이블      남
16  엄태구          팀호프      남
17  구교환        나무엑터스      남
18  지예은    S&A엔터테인먼트      여

In [8]:
df_copy = df.copy()
df_copy

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [ ]:
df_copy['height']

0     190.3
1     182.2
2     183.0
3     173.0
4     178.0
5     164.0
6     185.0
7     163.0
8       NaN
9     180.0
10    178.0
11    184.0
12    178.0
13    176.0
14    183.0
15    182.0
16    181.0
17    182.0
18    171.0
19      NaN
Name: height, dtype: float64

In [ ]:
# fillna(): 결측값을 채워주는 함수
df_copy['height'].fillna(0)

0     190.3
1     182.2
2     183.0
3     173.0
4     178.0
5     164.0
6     185.0
7     163.0
8       0.0
9     180.0
10    178.0
11    184.0
12    178.0
13    176.0
14    183.0
15    182.0
16    181.0
17    182.0
18    171.0
19      0.0
Name: height, dtype: float64

In [ ]:
df_copy['height']

0     190.3
1     182.2
2     183.0
3     173.0
4     178.0
5     164.0
6     185.0
7     163.0
8       NaN
9     180.0
10    178.0
11    184.0
12    178.0
13    176.0
14    183.0
15    182.0
16    181.0
17    182.0
18    171.0
19      NaN
Name: height, dtype: float64

In [ ]:
height = df_copy['height'].mean()
height

np.float64(178.52777777777777)

In [ ]:
df_copy['height'] = df_copy['height'].fillna(height)
df_copy['height']

0     190.300000
1     182.200000
2     183.000000
3     173.000000
4     178.000000
5     164.000000
6     185.000000
7     163.000000
8     178.527778
9     180.000000
10    178.000000
11    184.000000
12    178.000000
13    176.000000
14    183.000000
15    182.000000
16    181.000000
17    182.000000
18    171.000000
19    178.527778
Name: height, dtype: float64

In [ ]:
df_copy = df.copy()
df_copy['height']

0     190.3
1     182.2
2     183.0
3     173.0
4     178.0
5     164.0
6     185.0
7     163.0
8       NaN
9     180.0
10    178.0
11    184.0
12    178.0
13    176.0
14    183.0
15    182.0
16    181.0
17    182.0
18    171.0
19      NaN
Name: height, dtype: float64

### ※ 평균과 중앙값
평균(Mean)은 데이터의 모든 값을 더한 뒤 데이터 개수로 나눈 값으로, 전체 데이터의 중심적인 경향을 나타내는 대표적인 통계값입니다. 예를 들어 [10, 20, 30]의 평균은 (10+20+30)/3 = 20입니다. 반면 중앙값(Median)은 데이터를 크기순으로 정렬했을 때 가장 가운데 위치한 값을 의미하며, 이상치(Outlier)의 영향을 적게 받는 특징이 있습니다. 예를 들어 [10, 20, 30]의 중앙값은 20입니다. 만약 데이터 개수가 짝수라 가운데 값이 두 개라면, 두 가운데 값의 평균을 중앙값으로 사용합니다. 예를 들어 [10, 20, 30, 40]에서는 가운데 값인 20과 30의 평균인 25가 중앙값이 됩니다. 따라서 평균은 전체 데이터를 모두 반영하는 대표값이고, 중앙값은 데이터의 정중앙 위치를 나타내는 대표값이라고 할 수 있습니다.

In [ ]:
height = df_copy['height'].median() # 50%값, 중위
height

np.float64(180.5)

In [ ]:
df_copy['height'] = df_copy['height'].fillna(height)
df_copy['height']

0     190.3
1     182.2
2     183.0
3     173.0
4     178.0
5     164.0
6     185.0
7     163.0
8     180.5
9     180.0
10    178.0
11    184.0
12    178.0
13    176.0
14    183.0
15    182.0
16    181.0
17    182.0
18    171.0
19    180.5
Name: height, dtype: float64

In [ ]:
# 원본 데이터 복원
df_copy = df.copy()
df_copy

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10     NaN     B   831169
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
19  전지현       이음해시태그      여  1981-10-30     NaN     B   358271

In [ ]:
# dropna(): 결측값이 있는 행 또는 열을 제거. 결측값이 한개라도 있는 경우 삭제
# axis=0 (행 삭제) -> 기본값
df_copy.dropna()

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673

In [ ]:
df_copy.dropna(axis=1) # 결측값이 있는 열을 제거

   name      company gender    birthday    brand
0   변우석     바로엔터테인먼트      남  1991-10-31  3762141
1   임영웅        물고기뮤직      남  1991-06-16  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29  2831201
4   유재석          안테나      남  1972-08-14  2015312
5   김연아        올댓스포츠      여  1990-09-05  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20  1015456
7   고윤정          MAA      여  1996-04-22   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10   831169
9   이정재      아티스트컴퍼니      남  1972-12-15   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   651035
11   공유      매니지먼트 숲      남  1979-07-10   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   486700
14  김도영     KIA 타이거즈      남  2003-10-02   481761
15  박보검       더블랙레이블      남  1993-06-16   451540
16  엄태구          팀호프      남  1983-11-09   380064
17  구교환        나무엑터스      남  1982-12-14   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   370543
19  전지현       이음해시태그      여  1981-10-30   358271

***
# **7. 행, 열 추가 및 삭제**

In [ ]:
df_copy

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10     NaN     B   831169
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
19  전지현       이음해시태그      여  1981-10-30     NaN     B   358271

In [ ]:
dic = {
    'name': '김사과',
    'company': '애플',
    'gender': '여자',
    'birthday': '2000-01-01',
    'height': 160.0,
    'blood': 'A',
    'brand': 1234567
}

In [ ]:
# ⭐
df_copy.loc[len(df_copy)] = dic
df_copy

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10     NaN     B   831169
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
19  전지현       이음해시태그      여  1981-10-30     NaN     B   358271
20  김사과           애플     여자  2000-01-01   160.0     A  1234567

In [ ]:
df_copy['nation'] = '대한민국'
df_copy.head()

  name    company gender    birthday  height blood    brand nation
0  변우석   바로엔터테인먼트      남  1991-10-31   190.3     B  3762141   대한민국
1  임영웅      물고기뮤직      남  1991-06-16   182.2     A  3349309   대한민국
2  손흥민  로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512   대한민국
3  박지훈   YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201   대한민국
4  유재석        안테나      남  1972-08-14   178.0     B  2015312   대한민국

In [ ]:
df_copy.tail()

   name    company gender    birthday  height blood    brand nation
16  엄태구        팀호프      남  1983-11-09   181.0     O   380064   대한민국
17  구교환      나무엑터스      남  1982-12-14   182.0     A   371673   대한민국
18  지예은  S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543   대한민국
19  전지현     이음해시태그      여  1981-10-30     NaN     B   358271   대한민국
20  김사과         애플     여자  2000-01-01   160.0     A  1234567   대한민국

In [ ]:
df_copy.loc[df_copy['name'] == '김사과', 'nation'] = '미국'
df_copy.tail()

   name    company gender    birthday  height blood    brand nation
16  엄태구        팀호프      남  1983-11-09   181.0     O   380064   대한민국
17  구교환      나무엑터스      남  1982-12-14   182.0     A   371673   대한민국
18  지예은  S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543   대한민국
19  전지현     이음해시태그      여  1981-10-30     NaN     B   358271   대한민국
20  김사과         애플     여자  2000-01-01   160.0     A  1234567     미국

In [ ]:
# 행 제거하기
df_copy.drop(20, axis=0) # 0: 행, 1: 열 (행 20번 삭제)

   name      company gender    birthday  height blood    brand nation
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141   대한민국
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309   대한민국
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512   대한민국
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201   대한민국
4   유재석          안테나      남  1972-08-14   178.0     B  2015312   대한민국
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281   대한민국
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456   대한민국
7   고윤정          MAA      여  1996-04-22   163.0     B   855724   대한민국
8   김혜윤      아티스트컴퍼니      여  1996-11-10     NaN     B   831169   대한민국
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985   대한민국
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035   대한민국
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519   대한민국
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485   대한민국
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700   대한민국
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761   대한민국
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540   대한민국
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064   대한민국
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673   대한민국
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543   대한민국
19  전지현       이음해시태그      여  1981-10-30     NaN     B   358271   대한민국

In [ ]:
df_copy.tail()

   name    company gender    birthday  height blood    brand nation
16  엄태구        팀호프      남  1983-11-09   181.0     O   380064   대한민국
17  구교환      나무엑터스      남  1982-12-14   182.0     A   371673   대한민국
18  지예은  S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543   대한민국
19  전지현     이음해시태그      여  1981-10-30     NaN     B   358271   대한민국
20  김사과         애플     여자  2000-01-01   160.0     A  1234567     미국

In [ ]:
df_copy.drop([1, 3, 5, 7, 20], axis=0)

   name      company gender    birthday  height blood    brand nation
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141   대한민국
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512   대한민국
4   유재석          안테나      남  1972-08-14   178.0     B  2015312   대한민국
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456   대한민국
8   김혜윤      아티스트컴퍼니      여  1996-11-10     NaN     B   831169   대한민국
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985   대한민국
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035   대한민국
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519   대한민국
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485   대한민국
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700   대한민국
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761   대한민국
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540   대한민국
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064   대한민국
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673   대한민국
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543   대한민국
19  전지현       이음해시태그      여  1981-10-30     NaN     B   358271   대한민국

In [ ]:
# 열 제거하기
df_copy.drop('nation', axis=1)

   name      company gender    birthday  height blood    brand
0   변우석     바로엔터테인먼트      남  1991-10-31   190.3     B  3762141
1   임영웅        물고기뮤직      남  1991-06-16   182.2     A  3349309
2   손흥민    로스앤젤레스 FC      남  1992-07-08   183.0    AB  3067512
3   박지훈     YY엔터테인먼트      남  1999-05-29   173.0    AB  2831201
4   유재석          안테나      남  1972-08-14   178.0     B  2015312
5   김연아        올댓스포츠      여  1990-09-05   164.0     O  1085281
6   이정후  샌프란시스코 자이언츠      남  1998-08-20   185.0     A  1015456
7   고윤정          MAA      여  1996-04-22   163.0     B   855724
8   김혜윤      아티스트컴퍼니      여  1996-11-10     NaN     B   831169
9   이정재      아티스트컴퍼니      남  1972-12-15   180.0     B   664985
10  마동석    빅펀치엔터테인먼트      남  1971-03-01   178.0     O   651035
11   공유      매니지먼트 숲      남  1979-07-10   184.0     A   561519
12  이준호    JYP엔터테인먼트      남  1990-01-25   178.0     A   543485
13  이찬원     티엔엔터테인먼트      남  1996-11-01   176.0     B   486700
14  김도영     KIA 타이거즈      남  2003-10-02   183.0   NaN   481761
15  박보검       더블랙레이블      남  1993-06-16   182.0     O   451540
16  엄태구          팀호프      남  1983-11-09   181.0     O   380064
17  구교환        나무엑터스      남  1982-12-14   182.0     A   371673
18  지예은    S&A엔터테인먼트      여  1994-07-26   171.0   NaN   370543
19  전지현       이음해시태그      여  1981-10-30     NaN     B   358271
20  김사과           애플     여자  2000-01-01   160.0     A  1234567

In [ ]:
df_copy.drop(['nation', 'company'], axis=1)

   name gender    birthday  height blood    brand
0   변우석      남  1991-10-31   190.3     B  3762141
1   임영웅      남  1991-06-16   182.2     A  3349309
2   손흥민      남  1992-07-08   183.0    AB  3067512
3   박지훈      남  1999-05-29   173.0    AB  2831201
4   유재석      남  1972-08-14   178.0     B  2015312
5   김연아      여  1990-09-05   164.0     O  1085281
6   이정후      남  1998-08-20   185.0     A  1015456
7   고윤정      여  1996-04-22   163.0     B   855724
8   김혜윤      여  1996-11-10     NaN     B   831169
9   이정재      남  1972-12-15   180.0     B   664985
10  마동석      남  1971-03-01   178.0     O   651035
11   공유      남  1979-07-10   184.0     A   561519
12  이준호      남  1990-01-25   178.0     A   543485
13  이찬원      남  1996-11-01   176.0     B   486700
14  김도영      남  2003-10-02   183.0   NaN   481761
15  박보검      남  1993-06-16   182.0     O   451540
16  엄태구      남  1983-11-09   181.0     O   380064
17  구교환      남  1982-12-14   182.0     A   371673
18  지예은      여  1994-07-26   171.0   NaN   370543
19  전지현      여  1981-10-30     NaN     B   358271
20  김사과     여자  2000-01-01   160.0     A  1234567

***
# **8. 통계함수**

In [ ]:
# df_copy데이터의 height를 가져와서 합계, 개수, 평균, 중앙값, 최대값, 최소값, 분산, 표준편차 출력
print(df_copy['height'].sum()) # 합계
print(df_copy['height'].count()) # 개수, NaN은 포함하지 않음
print(df_copy['height'].mean()) # 평균
print(df_copy['height'].median()) # 중앙값
print(df_copy['height'].max()) # 최대값
print(df_copy['height'].min()) # 최소값
print(df_copy['height'].var()) # 분산
print(df_copy['height'].std()) # 표준편차

3373.5
19
177.55263157894737
180.0
190.3
160.0
64.8959649122807
8.055803182320227

### ※ 분산과 표준편차
분산(Variance)은 데이터가 평균으로부터 얼마나 퍼져 있는지를 수치로 나타낸 값으로, 각 데이터와 평균의 차이를 제곱한 뒤 평균을 내어 계산합니다. 값이 클수록 데이터의 흩어짐이 크다는 의미이며, 값이 작을수록 데이터가 평균 근처에 모여 있다는 뜻입니다. 하지만 분산은 차이를 제곱해서 계산하기 때문에 단위가 원래 데이터와 달라진다는 단점이 있습니다. 이를 해결하기 위해 사용하는 것이 표준편차(Standard Deviation)이며, 표준편차는 분산에 제곱근(sqrt)을 취한 값입니다. 따라서 원래 데이터와 같은 단위를 사용하므로 해석이 더 직관적입니다.

<img src = "./images/분산과표준편차.png" width = 500>

In [ ]:
# groupby(): 데이터를 그룹으로 묶어 분석할 때 사용
df_copy.groupby('blood')        # <pandas.api.typing.DataFrameGroupBy object at 0x000002A148D8FBC0>

# 그룹 객체 (주소 출력)

In [ ]:
# 그룹을 맺으면 통계함수를 사용할 수 있음 (Nan은 값으로 치지 않음)
df_copy.groupby('blood').count()

       name  company  gender  birthday  height  brand  nation
blood
A         6        6       6         6       6      6       6
AB        2        2       2         2       2      2       2
B         7        7       7         7       5      7       7
O         4        4       4         4       4      4       4

In [ ]:
# numeric_only=True : 평균을 낼 수 있는 수치 데이터만
df_copy.groupby('blood').mean(numeric_only=True)

           height         brand
blood
A      178.533333  1.179335e+06
AB     178.000000  2.949356e+06
B      177.460000  1.282043e+06
O      176.250000  6.419800e+05

In [ ]:
df_copy.groupby('blood').sum(numeric_only=True)

       height    brand
blood
A      1071.2  7076009
AB      356.0  5898713
B       887.3  8974302
O       705.0  2567920

In [9]:
# blood와 gender로 그룹화
df_copy.groupby(['blood','gender']).mean(numeric_only=True)

KeyError: 'blood'

In [ ]:
df_copy.groupby(['blood','gender'])['height'].mean()

# df_copy.groupby(['gender', 'blood'])['height'].mean()

blood  gender
A      남         182.240000
       여자        160.000000
AB     남         178.000000
B      남         181.075000
       여         163.000000
O      남         180.333333
       여         164.000000
Name: height, dtype: float64

In [ ]:
df_copy['blood']

0       B
1       A
2      AB
3      AB
4       B
5       O
6       A
7       B
8       B
9       B
10      O
11      A
12      A
13      B
14    NaN
15      O
16      O
17      A
18    NaN
19      B
20      A
Name: blood, dtype: str

In [ ]:
# drop_duplicates(): 중복된 데이터를 제거, keep='first' 기본값
# df_copy['blood'].drop_duplicates(keep='last')
df_copy['blood'].drop_duplicates()

# 데이터의 개수가 많을 때 컬럼에 종류가 어떤게 있는지 궁금할 때 사용가능

0       B
1       A
2      AB
5       O
14    NaN
Name: blood, dtype: str

In [ ]:
# value_counts(): 열의 각 값에 대한 데이터의 개수를 반환. 기본은 NaN을 생략
# df_copy['blood'].value_counts(dropna=False) # NaN를 포함
df_copy['blood'].value_counts()

# drop_duplicate보다는 value_counts를 더 많이 사용하기는 함(데이터 개수도 확인 가능하긴 때문에)

blood
B     7
A     6
O     4
AB    2
Name: count, dtype: int64

***
# **9. 데이터프레임 다루기**

In [ ]:
df1 = pd.read_csv('./광고모델_브랜드평판.csv')
df2 = pd.read_csv('./광고모델_상세정보.csv')

In [ ]:
df1

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [ ]:
df2

     이름          연봉      주소
0   변우석  2600000000  경기 성남시
1   임영웅  2100000000  경기 성남시
2   손흥민  2400000000  경기 수원시
3   박지훈  3700000000  대구 수성구
4   유재석  3100000000  서울 송파구
5   김연아   600000000  경기 수원시
6   이정후  2600000000   광주 서구
7   고윤정  3700000000  경기 수원시
8   김혜윤  3200000000  대구 수성구
9   이정재  2300000000  서울 송파구
10  마동석  4800000000  서울 용산구
11   공유  2600000000  경기 수원시
12  이준호  1800000000  대구 수성구
13  이찬원  4700000000   광주 서구
14  김도영  4000000000   광주 서구
15  박보검  1900000000  서울 용산구
16  엄태구  3900000000  서울 강남구
17  구교환  1800000000  서울 용산구
18  지예은  2700000000  서울 마포구
19  전지현  1200000000  서울 송파구

In [ ]:
df1_copy = df1.copy()
df2_copy = df2.copy()

In [ ]:
pd.concat([df1, df1_copy]) # axis=0 (기본값)

# 인덱스가 중복되어 쓸모 없어짐

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [ ]:
df1_concat = pd.concat([df1, df1_copy])

# reset_index(): index를 새롭게 적용
# drop=True 옵션을 사용하여 기존 index가 컬럼으로 만들어지는 것을 방지(지우고 출력도 해보기)
df1_concat.reset_index(drop=True)

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271
20  변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
21  임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
22  손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
23  박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
24  유재석          안테나  남  1972-08-14    178cm    B  2,015,312
25  김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
26  이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
27  고윤정          MAA  여  1996-04-22    163cm    B    855,724
28  김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
29  이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
30  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
31   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
32  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
33  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
34  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
35  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
36  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
37  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
38  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
39  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [ ]:
pd.concat([df1_copy, df2_copy], axis=1) # 같은 index와 결합 (df1_copy와 df2_copy는 현재 같은 인덱스 사용중이기 때문에 문제없이 잘 나옴)

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",변우석,2600000000,경기 성남시
1,임영웅,물고기뮤직,남,1991-06-16,182.2cm,A,"3,349,309",임영웅,2100000000,경기 성남시
2,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",손흥민,2400000000,경기 수원시
3,박지훈,YY엔터테인먼트,남,1999-05-29,173cm,AB,"2,831,201",박지훈,3700000000,대구 수성구
4,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",유재석,3100000000,서울 송파구
5,김연아,올댓스포츠,여,1990-09-05,164cm,O,"1,085,281",김연아,600000000,경기 수원시
6,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",이정후,2600000000,광주 서구
7,고윤정,MAA,여,1996-04-22,163cm,B,"855,724",고윤정,3700000000,경기 수원시
8,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",김혜윤,3200000000,대구 수성구
9,이정재,아티스트컴퍼니,남,1972-12-15,180cm,B,"664,985",이정재,2300000000,서울 송파구
10,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",마동석,4800000000,서울 용산구
11,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",공유,2600000000,경기 수원시
12,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",이준호,1800000000,대구 수성구
13,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",이찬원,4700000000,광주 서구
14,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",김도영,4000000000,광주 서구
15,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",박보검,1900000000,서울 용산구
16,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",엄태구,3900000000,서울 강남구
17,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",구교환,1800000000,서울 용산구
18,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",지예은,2700000000,서울 마포구
19,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",전지현,1200000000,서울 송파구

In [ ]:
# 인덱스가 1,3,5,7,9인 데이터 삭제
df2_copy = df2_copy.drop([1, 3, 5, 7, 9])
df2_copy

     이름          연봉      주소
0   변우석  2600000000  경기 성남시
2   손흥민  2400000000  경기 수원시
4   유재석  3100000000  서울 송파구
6   이정후  2600000000   광주 서구
8   김혜윤  3200000000  대구 수성구
10  마동석  4800000000  서울 용산구
11   공유  2600000000  경기 수원시
12  이준호  1800000000  대구 수성구
13  이찬원  4700000000   광주 서구
14  김도영  4000000000   광주 서구
15  박보검  1900000000  서울 용산구
16  엄태구  3900000000  서울 강남구
17  구교환  1800000000  서울 용산구
18  지예은  2700000000  서울 마포구
19  전지현  1200000000  서울 송파구

In [ ]:
pd.concat([df1_copy, df2_copy], axis=1)     # 없는 값은 NaN

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",변우석,2.600000e+09,경기 성남시
1,임영웅,물고기뮤직,남,1991-06-16,182.2cm,A,"3,349,309",NaN,NaN,NaN
2,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",손흥민,2.400000e+09,경기 수원시
3,박지훈,YY엔터테인먼트,남,1999-05-29,173cm,AB,"2,831,201",NaN,NaN,NaN
4,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",유재석,3.100000e+09,서울 송파구
5,김연아,올댓스포츠,여,1990-09-05,164cm,O,"1,085,281",NaN,NaN,NaN
6,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",이정후,2.600000e+09,광주 서구
7,고윤정,MAA,여,1996-04-22,163cm,B,"855,724",NaN,NaN,NaN
8,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",김혜윤,3.200000e+09,대구 수성구
9,이정재,아티스트컴퍼니,남,1972-12-15,180cm,B,"664,985",NaN,NaN,NaN
10,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",마동석,4.800000e+09,서울 용산구
11,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",공유,2.600000e+09,경기 수원시
12,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",이준호,1.800000e+09,대구 수성구
13,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",이찬원,4.700000e+09,광주 서구
14,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",김도영,4.000000e+09,광주 서구
15,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",박보검,1.900000e+09,서울 용산구
16,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",엄태구,3.900000e+09,서울 강남구
17,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",구교환,1.800000e+09,서울 용산구
18,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",지예은,2.700000e+09,서울 마포구
19,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",전지현,1.200000e+09,서울 송파구

In [ ]:
# 인덱스를 다시 지정
df2_copy = df2_copy.reset_index(drop=True)
df2_copy

     이름          연봉      주소
0   변우석  2600000000  경기 성남시
1   손흥민  2400000000  경기 수원시
2   유재석  3100000000  서울 송파구
3   이정후  2600000000   광주 서구
4   김혜윤  3200000000  대구 수성구
5   마동석  4800000000  서울 용산구
6    공유  2600000000  경기 수원시
7   이준호  1800000000  대구 수성구
8   이찬원  4700000000   광주 서구
9   김도영  4000000000   광주 서구
10  박보검  1900000000  서울 용산구
11  엄태구  3900000000  서울 강남구
12  구교환  1800000000  서울 용산구
13  지예은  2700000000  서울 마포구
14  전지현  1200000000  서울 송파구

In [ ]:
# 새로운 데이터 맨 아래에 추가
dic = {
    '이름': '김사과',
    '연봉': 9900000000,
    '주소': '서울 강남구'
}

df2_copy.loc[len(df2_copy)] = dic
df2_copy

     이름          연봉      주소
0   변우석  2600000000  경기 성남시
1   손흥민  2400000000  경기 수원시
2   유재석  3100000000  서울 송파구
3   이정후  2600000000   광주 서구
4   김혜윤  3200000000  대구 수성구
5   마동석  4800000000  서울 용산구
6    공유  2600000000  경기 수원시
7   이준호  1800000000  대구 수성구
8   이찬원  4700000000   광주 서구
9   김도영  4000000000   광주 서구
10  박보검  1900000000  서울 용산구
11  엄태구  3900000000  서울 강남구
12  구교환  1800000000  서울 용산구
13  지예은  2700000000  서울 마포구
14  전지현  1200000000  서울 송파구
15  김사과  9900000000  서울 강남구

In [ ]:
# 인덱스가 같은 것 끼리 그냥 순서대로 합침
pd.concat([df1_copy, df2_copy], axis=1)

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",변우석,2.600000e+09,경기 성남시
1,임영웅,물고기뮤직,남,1991-06-16,182.2cm,A,"3,349,309",손흥민,2.400000e+09,경기 수원시
2,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",유재석,3.100000e+09,서울 송파구
3,박지훈,YY엔터테인먼트,남,1999-05-29,173cm,AB,"2,831,201",이정후,2.600000e+09,광주 서구
4,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",김혜윤,3.200000e+09,대구 수성구
5,김연아,올댓스포츠,여,1990-09-05,164cm,O,"1,085,281",마동석,4.800000e+09,서울 용산구
6,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",공유,2.600000e+09,경기 수원시
7,고윤정,MAA,여,1996-04-22,163cm,B,"855,724",이준호,1.800000e+09,대구 수성구
8,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",이찬원,4.700000e+09,광주 서구
9,이정재,아티스트컴퍼니,남,1972-12-15,180cm,B,"664,985",김도영,4.000000e+09,광주 서구
10,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",박보검,1.900000e+09,서울 용산구
11,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",엄태구,3.900000e+09,서울 강남구
12,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",구교환,1.800000e+09,서울 용산구
13,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",지예은,2.700000e+09,서울 마포구
14,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",전지현,1.200000e+09,서울 송파구
15,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",김사과,9.900000e+09,서울 강남구
16,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",NaN,NaN,NaN
17,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",NaN,NaN,NaN
18,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",NaN,NaN,NaN
19,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",NaN,NaN,NaN

In [ ]:
# merge(): 특정 고유한 키(unique, id)값을 기준으로 합침
# merge(데이터프레임1, 데이터프레임2, on='유니크값', how='병합의 기준')
# 병합의 기준: left, right, inner, cross⭐
# 데이터베이스에서 조인연산과 같음
# 김사과 데이터는 왼쪽에 없으니까 보이지 않음
pd.merge(df1_copy, df2_copy, on='이름', how='left')

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",2.600000e+09,경기 성남시
1,임영웅,물고기뮤직,남,1991-06-16,182.2cm,A,"3,349,309",NaN,NaN
2,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",2.400000e+09,경기 수원시
3,박지훈,YY엔터테인먼트,남,1999-05-29,173cm,AB,"2,831,201",NaN,NaN
4,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",3.100000e+09,서울 송파구
5,김연아,올댓스포츠,여,1990-09-05,164cm,O,"1,085,281",NaN,NaN
6,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",2.600000e+09,광주 서구
7,고윤정,MAA,여,1996-04-22,163cm,B,"855,724",NaN,NaN
8,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",3.200000e+09,대구 수성구
9,이정재,아티스트컴퍼니,남,1972-12-15,180cm,B,"664,985",NaN,NaN
10,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",4.800000e+09,서울 용산구
11,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",2.600000e+09,경기 수원시
12,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",1.800000e+09,대구 수성구
13,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",4.700000e+09,광주 서구
14,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",4.000000e+09,광주 서구
15,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",1.900000e+09,서울 용산구
16,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",3.900000e+09,서울 강남구
17,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",1.800000e+09,서울 용산구
18,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",2.700000e+09,서울 마포구
19,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",1.200000e+09,서울 송파구

In [ ]:
pd.merge(df1_copy, df2_copy, on='이름', how='right')

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",2600000000,경기 성남시
1,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",2400000000,경기 수원시
2,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",3100000000,서울 송파구
3,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",2600000000,광주 서구
4,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",3200000000,대구 수성구
5,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",4800000000,서울 용산구
6,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",2600000000,경기 수원시
7,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",1800000000,대구 수성구
8,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",4700000000,광주 서구
9,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",4000000000,광주 서구
10,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",1900000000,서울 용산구
11,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",3900000000,서울 강남구
12,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",1800000000,서울 용산구
13,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",2700000000,서울 마포구
14,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",1200000000,서울 송파구
15,김사과,NaN,NaN,NaN,NaN,NaN,NaN,9900000000,서울 강남구

In [ ]:
# 양쪽 다 있는 경우만 합침 (-> NaN이 발생하지 않겠죠?)
pd.merge(df1_copy, df2_copy, on='이름', how='inner')

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",2600000000,경기 성남시
1,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",2400000000,경기 수원시
2,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",3100000000,서울 송파구
3,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",2600000000,광주 서구
4,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",3200000000,대구 수성구
5,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",4800000000,서울 용산구
6,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",2600000000,경기 수원시
7,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",1800000000,대구 수성구
8,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",4700000000,광주 서구
9,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",4000000000,광주 서구
10,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",1900000000,서울 용산구
11,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",3900000000,서울 강남구
12,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",1800000000,서울 용산구
13,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",2700000000,서울 마포구
14,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",1200000000,서울 송파구

In [ ]:
# 모든 경우의 짝을 다 출력
pd.merge(df1_copy, df2_copy, how='cross')

,이름_x,소속사,성별,생년월일,키,혈액형,브랜드평판지수,이름_y,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",변우석,2600000000,경기 성남시
1,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",손흥민,2400000000,경기 수원시
2,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",유재석,3100000000,서울 송파구
3,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",이정후,2600000000,광주 서구
4,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",김혜윤,3200000000,대구 수성구
...,...,...,...,...,...,...,...,...,...,...
315,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",엄태구,3900000000,서울 강남구
316,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",구교환,1800000000,서울 용산구
317,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",지예은,2700000000,서울 마포구
318,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",전지현,1200000000,서울 송파구
319,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",김사과,9900000000,서울 강남구

In [ ]:
# 컬럼 이름이 다른 경우
df2_copy.columns = ['성함', '연봉', '주소']
df2_copy

     성함          연봉      주소
0   변우석  2600000000  경기 성남시
1   손흥민  2400000000  경기 수원시
2   유재석  3100000000  서울 송파구
3   이정후  2600000000   광주 서구
4   김혜윤  3200000000  대구 수성구
5   마동석  4800000000  서울 용산구
6    공유  2600000000  경기 수원시
7   이준호  1800000000  대구 수성구
8   이찬원  4700000000   광주 서구
9   김도영  4000000000   광주 서구
10  박보검  1900000000  서울 용산구
11  엄태구  3900000000  서울 강남구
12  구교환  1800000000  서울 용산구
13  지예은  2700000000  서울 마포구
14  전지현  1200000000  서울 송파구
15  김사과  9900000000  서울 강남구

In [ ]:
# pd.merge(df1, df_right, on='이름', how='inner') KeyError: '이름'
# left 컬럼이름과 right 컬럼이름을 매칭시켜서 작성
pd.merge(df1_copy, df2_copy, left_on='이름', right_on='성함', how='inner')

,이름,소속사,성별,생년월일,키,혈액형,브랜드평판지수,성함,연봉,주소
0,변우석,바로엔터테인먼트,남,1991-10-31,190.3cm,B,"3,762,141",변우석,2600000000,경기 성남시
1,손흥민,로스앤젤레스 FC,남,1992-07-08,183cm,AB,"3,067,512",손흥민,2400000000,경기 수원시
2,유재석,안테나,남,1972-08-14,178cm,B,"2,015,312",유재석,3100000000,서울 송파구
3,이정후,샌프란시스코 자이언츠,남,1998-08-20,185cm,A,"1,015,456",이정후,2600000000,광주 서구
4,김혜윤,아티스트컴퍼니,여,1996-11-10,160cm,B,"831,169",김혜윤,3200000000,대구 수성구
5,마동석,빅펀치엔터테인먼트,남,1971-03-01,178cm,O,"651,035",마동석,4800000000,서울 용산구
6,공유,매니지먼트 숲,남,1979-07-10,184cm,A,"561,519",공유,2600000000,경기 수원시
7,이준호,JYP엔터테인먼트,남,1990-01-25,178cm,A,"543,485",이준호,1800000000,대구 수성구
8,이찬원,티엔엔터테인먼트,남,1996-11-01,176cm,B,"486,700",이찬원,4700000000,광주 서구
9,김도영,KIA 타이거즈,남,2003-10-02,183cm,NaN,"481,761",김도영,4000000000,광주 서구
10,박보검,더블랙레이블,남,1993-06-16,182cm,O,"451,540",박보검,1900000000,서울 용산구
11,엄태구,팀호프,남,1983-11-09,181cm,O,"380,064",엄태구,3900000000,서울 강남구
12,구교환,나무엑터스,남,1982-12-14,182cm,A,"371,673",구교환,1800000000,서울 용산구
13,지예은,S&A엔터테인먼트,여,1994-07-26,171cm,NaN,"370,543",지예은,2700000000,서울 마포구
14,전지현,이음해시태그,여,1981-10-30,173cm,B,"358,271",전지현,1200000000,서울 송파구

***
# **10. 날짜타입**

> 날짜 타입을 만든 이유 : 문자열로 날짜 계산하는 것이 어렵기 때문에 날짜 계산을 편하게 하기 위해

In [ ]:
df1_copy = df1.copy()
df1_copy

     이름          소속사 성별        생년월일        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  1991-10-31  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  1991-06-16  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남  1992-07-08    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남  1999-05-29    173cm   AB  2,831,201
4   유재석          안테나  남  1972-08-14    178cm    B  2,015,312
5   김연아        올댓스포츠  여  1990-09-05    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남  1998-08-20    185cm    A  1,015,456
7   고윤정          MAA  여  1996-04-22    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여  1996-11-10    160cm    B    831,169
9   이정재      아티스트컴퍼니  남  1972-12-15    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남  1971-03-01    178cm    O    651,035
11   공유      매니지먼트 숲  남  1979-07-10    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남  1990-01-25    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남  1996-11-01    176cm    B    486,700
14  김도영     KIA 타이거즈  남  2003-10-02    183cm  NaN    481,761
15  박보검       더블랙레이블  남  1993-06-16    182cm    O    451,540
16  엄태구          팀호프  남  1983-11-09    181cm    O    380,064
17  구교환        나무엑터스  남  1982-12-14    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여  1994-07-26    171cm  NaN    370,543
19  전지현       이음해시태그  여  1981-10-30    173cm    B    358,271

In [ ]:
df1_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     str
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: str(7)
memory usage: 1.2 KB

In [ ]:
df1_copy['생년월일']

0     1991-10-31
1     1991-06-16
2     1992-07-08
3     1999-05-29
4     1972-08-14
5     1990-09-05
6     1998-08-20
7     1996-04-22
8     1996-11-10
9     1972-12-15
10    1971-03-01
11    1979-07-10
12    1990-01-25
13    1996-11-01
14    2003-10-02
15    1993-06-16
16    1983-11-09
17    1982-12-14
18    1994-07-26
19    1981-10-30
Name: 생년월일, dtype: str

In [ ]:
# to_datatime(): str타입에서 datetime타입으로 변환
df1_copy['생년월일'] = pd.to_datetime(df1_copy['생년월일'])
print(type(df1_copy['생년월일']))
print(df1_copy['생년월일'].dtypes)

<class 'pandas.Series'>
datetime64[us]

In [ ]:
df1_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     datetime64[us]
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: datetime64[us](1), str(6)
memory usage: 1.2 KB

In [ ]:
df1_copy['생년월일'].dt.year

0     1991
1     1991
2     1992
3     1999
4     1972
5     1990
6     1998
7     1996
8     1996
9     1972
10    1971
11    1979
12    1990
13    1996
14    2003
15    1993
16    1983
17    1982
18    1994
19    1981
Name: 생년월일, dtype: int32

In [ ]:
df1_copy['생년월일'].dt.month

0     10
1      6
2      7
3      5
4      8
5      9
6      8
7      4
8     11
9     12
10     3
11     7
12     1
13    11
14    10
15     6
16    11
17    12
18     7
19    10
Name: 생년월일, dtype: int32

In [ ]:
df1_copy['생년월일'].dt.day

0     31
1     16
2      8
3     29
4     14
5      5
6     20
7     22
8     10
9     15
10     1
11    10
12    25
13     1
14     2
15    16
16     9
17    14
18    26
19    30
Name: 생년월일, dtype: int32

In [ ]:
df1_copy['생년월일'].dt.hour

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: 생년월일, dtype: int32

In [ ]:
df1_copy['생년월일'].dt.minute

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: 생년월일, dtype: int32

In [ ]:
df1_copy['생년월일'].dt.second

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: 생년월일, dtype: int32

In [ ]:
df1_copy['생년월일'].dt.dayofweek # 요일: 0(월요일) ~ 6(일요일)

0     3
1     6
2     2
3     5
4     0
5     2
6     3
7     0
8     6
9     4
10    0
11    1
12    3
13    4
14    3
15    2
16    2
17    1
18    1
19    4
Name: 생년월일, dtype: int32

In [ ]:
# 1년 중에 몇 주째인지
df1_copy['생년월일'].dt.isocalendar().week

0     44
1     24
2     28
3     21
4     33
5     36
6     34
7     17
8     45
9     50
10     9
11    28
12     4
13    44
14    40
15    24
16    45
17    50
18    30
19    44
Name: week, dtype: UInt32

In [ ]:
df1_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     datetime64[us]
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: datetime64[us](1), str(6)
memory usage: 1.2 KB

In [ ]:
df1_copy.select_dtypes(include='str') # 문자열 컬럼만 가져오기

     이름          소속사 성별        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남    173cm   AB  2,831,201
4   유재석          안테나  남    178cm    B  2,015,312
5   김연아        올댓스포츠  여    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남    185cm    A  1,015,456
7   고윤정          MAA  여    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여    160cm    B    831,169
9   이정재      아티스트컴퍼니  남    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남    178cm    O    651,035
11   공유      매니지먼트 숲  남    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남    176cm    B    486,700
14  김도영     KIA 타이거즈  남    183cm  NaN    481,761
15  박보검       더블랙레이블  남    182cm    O    451,540
16  엄태구          팀호프  남    181cm    O    380,064
17  구교환        나무엑터스  남    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여    171cm  NaN    370,543
19  전지현       이음해시태그  여    173cm    B    358,271

In [ ]:
df1_copy.select_dtypes(exclude='str') # 문자열 컬럼만 빼고 가져오기

         생년월일
0  1991-10-31
1  1991-06-16
2  1992-07-08
3  1999-05-29
4  1972-08-14
5  1990-09-05
6  1998-08-20
7  1996-04-22
8  1996-11-10
9  1972-12-15
10 1971-03-01
11 1979-07-10
12 1990-01-25
13 1996-11-01
14 2003-10-02
15 1993-06-16
16 1983-11-09
17 1982-12-14
18 1994-07-26
19 1981-10-30

In [ ]:
# 문자열을 가지고 있는 컬럼의 이름만 변수에 저장하여 출력
str_cols = df1_copy.select_dtypes(include='str').columns
str_cols

Index(['이름', '소속사', '성별', '키', '혈액형', '브랜드평판지수'], dtype='str')

In [ ]:
df1_copy[str_cols]

     이름          소속사 성별        키  혈액형    브랜드평판지수
0   변우석     바로엔터테인먼트  남  190.3cm    B  3,762,141
1   임영웅        물고기뮤직  남  182.2cm    A  3,349,309
2   손흥민    로스앤젤레스 FC  남    183cm   AB  3,067,512
3   박지훈     YY엔터테인먼트  남    173cm   AB  2,831,201
4   유재석          안테나  남    178cm    B  2,015,312
5   김연아        올댓스포츠  여    164cm    O  1,085,281
6   이정후  샌프란시스코 자이언츠  남    185cm    A  1,015,456
7   고윤정          MAA  여    163cm    B    855,724
8   김혜윤      아티스트컴퍼니  여    160cm    B    831,169
9   이정재      아티스트컴퍼니  남    180cm    B    664,985
10  마동석    빅펀치엔터테인먼트  남    178cm    O    651,035
11   공유      매니지먼트 숲  남    184cm    A    561,519
12  이준호    JYP엔터테인먼트  남    178cm    A    543,485
13  이찬원     티엔엔터테인먼트  남    176cm    B    486,700
14  김도영     KIA 타이거즈  남    183cm  NaN    481,761
15  박보검       더블랙레이블  남    182cm    O    451,540
16  엄태구          팀호프  남    181cm    O    380,064
17  구교환        나무엑터스  남    182cm    A    371,673
18  지예은    S&A엔터테인먼트  여    171cm  NaN    370,543
19  전지현       이음해시태그  여    173cm    B    358,271

***
# **11. 자주 사용하는 함수**

### 1. apply 
Pandas의 apply() 함수는 데이터프레임이나 시리즈의 데이터를 사용자 정의 함수 또는 내장 함수에 적용하여 새로운 값을 계산하거나 변환할 때 사용됩니다. 데이터를 행(row) 또는 열(column) 단위로 처리할 수 있는 강력한 도구입니다.

In [ ]:
df1_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     str
 1   소속사      20 non-null     str
 2   성별       20 non-null     str
 3   생년월일     20 non-null     datetime64[us]
 4   키        20 non-null     str
 5   혈액형      18 non-null     str
 6   브랜드평판지수  20 non-null     str
dtypes: datetime64[us](1), str(6)
memory usage: 1.2 KB

In [ ]:
def male_or_female(x):
    if x == '남':
        return 1
    elif x == '여':
        return 0
    else:
        return None

In [ ]:
print(male_or_female('남'))
print(male_or_female('여'))

1
0

In [ ]:
df1_copy['성별'].apply(male_or_female)

0     1
1     1
2     1
3     1
4     1
5     0
6     1
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    0
19    0
Name: 성별, dtype: int64

In [ ]:
# 함수나 람다식이다 결과는 똑같음
df1_copy['성별'].apply(lambda x: 1 if x == '남' else 0)

0     1
1     1
2     1
3     1
4     1
5     0
6     1
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    0
19    0
Name: 성별, dtype: int64

In [ ]:
# 파생 변수 (변수 = 컬럼)
# 성별에 의해 람다 계산 후 만들어진 파생 변수
df1_copy['성별2'] = df1_copy['성별'].apply(lambda x: 1 if x == '남' else 0)
df1_copy.head()

    이름        소속사 성별       생년월일        키 혈액형    브랜드평판지수  성별2
0  변우석   바로엔터테인먼트  남 1991-10-31  190.3cm   B  3,762,141    1
1  임영웅      물고기뮤직  남 1991-06-16  182.2cm   A  3,349,309    1
2  손흥민  로스앤젤레스 FC  남 1992-07-08    183cm  AB  3,067,512    1
3  박지훈   YY엔터테인먼트  남 1999-05-29    173cm  AB  2,831,201    1
4  유재석        안테나  남 1972-08-14    178cm   B  2,015,312    1

### 2. map 사용하기
Pandas의 map() 함수는 Series 객체에서 사용할 수 있는 함수로, 각 요소에 대해 함수나 매핑 규칙을 적용하여 새로운 값을 계산하거나 변환할 때 사용됩니다. map()은 데이터의 각 요소를 순회하며 특정 작업을 수행하므로, 데이터를 가공하거나 변환하는 데 유용합니다.

In [ ]:
map_gender = {'남':1, '여':0}

df1_copy['성별'].map(map_gender)

0     1
1     1
2     1
3     1
4     1
5     0
6     1
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    0
19    0
Name: 성별, dtype: int64

In [ ]:
df1_copy['성별3'] = df1_copy['성별'].map(map_gender)
df1_copy.head()

    이름        소속사 성별       생년월일        키 혈액형    브랜드평판지수  성별2  성별3
0  변우석   바로엔터테인먼트  남 1991-10-31  190.3cm   B  3,762,141    1    1
1  임영웅      물고기뮤직  남 1991-06-16  182.2cm   A  3,349,309    1    1
2  손흥민  로스앤젤레스 FC  남 1992-07-08    183cm  AB  3,067,512    1    1
3  박지훈   YY엔터테인먼트  남 1999-05-29    173cm  AB  2,831,201    1    1
4  유재석        안테나  남 1972-08-14    178cm   B  2,015,312    1    1

***
# **12. 데이터프레임의 산술연산**

In [ ]:
df1 = pd.DataFrame({
    '파이썬':[60, 70, 80, 90, 95],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

df1

   파이썬  데이터분석  머신러닝딥러닝
0   60     40       35
1   70     60       40
2   80     70       30
3   90     55       70
4   95     87       55

In [ ]:
print(df1['파이썬'].dtypes)
print(type(df1['파이썬']))

int64
<class 'pandas.Series'>

In [ ]:
df1['파이썬'] + df1['데이터분석'] + df1['머신러닝딥러닝']

0    135
1    170
2    180
3    215
4    237
dtype: int64

In [ ]:
# df1에 총점, 평균이라는 파생변수를 만들고 파생변수에 총점, 평균을 구해서 저장
df1['총점'] = df1['파이썬'] + df1['데이터분석'] + df1['머신러닝딥러닝']
df1['평균'] = df1['총점'] / 3
df1

   파이썬  데이터분석  머신러닝딥러닝   총점         평균
0   60     40       35  135  45.000000
1   70     60       40  170  56.666667
2   80     70       30  180  60.000000
3   90     55       70  215  71.666667
4   95     87       55  237  79.000000

In [ ]:
print(df1['파이썬'].sum()) # df1['파이썬'].sum(axis=0)
print(df1['파이썬'].mean())

395
79.0

In [ ]:
print(df1.sum())
print(df1.mean())

파이썬        395.000000
데이터분석      312.000000
머신러닝딥러닝    230.000000
총점         937.000000
평균         312.333333
dtype: float64
파이썬         79.000000
데이터분석       62.400000
머신러닝딥러닝     46.000000
총점         187.400000
평균          62.466667
dtype: float64

In [ ]:
df1 = pd.DataFrame({
    '파이썬':[60, 70, 80, 90, 95],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

df2 = pd.DataFrame({
    '파이썬':['C', 'B', 'B', 'A', 'A'],
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

In [ ]:
# df1 + df2 # TypeError: unsupported operand type(s) for +: 'int' and 'str'
df1 + 10
# df2 + 10 # TypeError: can only concatenate str (not "int") to str

   파이썬  데이터분석  머신러닝딥러닝
0   70     50       45
1   80     70       50
2   90     80       40
3  100     65       80
4  105     97       65

In [ ]:
df1 = pd.DataFrame({
    '데이터분석':[40, 60, 70, 55, 87],
    '머신러닝딥러닝':[35, 40, 30, 70, 55]
})

df2 = pd.DataFrame({
    '데이터분석':[40, 60, 70, 55],
    '머신러닝딥러닝':[35, 40, 30, 70]
})

In [ ]:
df1 + df2 # 행의 갯수가 다를 경우 빠진 데이터를 NaN으로 취급하기 때문에 결과는 NaN

   데이터분석  머신러닝딥러닝
0   80.0     70.0
1  120.0     80.0
2  140.0     60.0
3  110.0    140.0
4    NaN      NaN

In [ ]:
df_copy = df1.copy()
df1_copy

     이름          소속사 성별       생년월일        키  혈액형    브랜드평판지수  성별2  성별3
0   변우석     바로엔터테인먼트  남 1991-10-31  190.3cm    B  3,762,141    1    1
1   임영웅        물고기뮤직  남 1991-06-16  182.2cm    A  3,349,309    1    1
2   손흥민    로스앤젤레스 FC  남 1992-07-08    183cm   AB  3,067,512    1    1
3   박지훈     YY엔터테인먼트  남 1999-05-29    173cm   AB  2,831,201    1    1
4   유재석          안테나  남 1972-08-14    178cm    B  2,015,312    1    1
5   김연아        올댓스포츠  여 1990-09-05    164cm    O  1,085,281    0    0
6   이정후  샌프란시스코 자이언츠  남 1998-08-20    185cm    A  1,015,456    1    1
7   고윤정          MAA  여 1996-04-22    163cm    B    855,724    0    0
8   김혜윤      아티스트컴퍼니  여 1996-11-10    160cm    B    831,169    0    0
9   이정재      아티스트컴퍼니  남 1972-12-15    180cm    B    664,985    1    1
10  마동석    빅펀치엔터테인먼트  남 1971-03-01    178cm    O    651,035    1    1
11   공유      매니지먼트 숲  남 1979-07-10    184cm    A    561,519    1    1
12  이준호    JYP엔터테인먼트  남 1990-01-25    178cm    A    543,485    1    1
13  이찬원     티엔엔터테인먼트  남 1996-11-01    176cm    B    486,700    1    1
14  김도영     KIA 타이거즈  남 2003-10-02    183cm  NaN    481,761    1    1
15  박보검       더블랙레이블  남 1993-06-16    182cm    O    451,540    1    1
16  엄태구          팀호프  남 1983-11-09    181cm    O    380,064    1    1
17  구교환        나무엑터스  남 1982-12-14    182cm    A    371,673    1    1
18  지예은    S&A엔터테인먼트  여 1994-07-26    171cm  NaN    370,543    0    0
19  전지현       이음해시태그  여 1981-10-30    173cm    B    358,271    0    0

***
# **11. get_dummies**
머신러닝 모델은 숫자 데이터는 처리할 수 있지만 문자열 데이터는 직접 처리할 수 없습니다. 따라서 문자열로 이루어진 범주형 데이터를 숫자 형태로 변환하는 과정이 필요하며, 이때 많이 사용하는 방법이 원-핫 인코딩(One-Hot Encoding) 입니다. Pandas에서는 pd.get_dummies() 함수를 이용해 쉽게 원-핫 인코딩을 수행할 수 있습니다.

### 원-핫 인코딩
범주형 데이터를 각 항목별로 새로운 컬럼으로 분리하고, 해당 값이면 1, 아니면 0을 부여하는 방법입니다. 원-핫 인코딩은 범주형 데이터(Categorical Data) 에 적용합니다. 범주형 데이터란 데이터의 값이 크기나 순서를 의미하는 것이 아니라 **단순히 종류(Category)**를 나타내는 데이터를 말합니다.

![범주형데이터](./images/범주형데이터.png)

> 👉 문자열이라고 무조건 원-핫 인코딩하는 것은 아닙니다. 예를 들어 Pandas에서는 문자열(str) 타입으로 인식할 수 있지만, 생년월일은 시간의 흐름이라는 의미가 있습니다. 따라서 단순히 문자열이라는 이유만으로 원-핫 인코딩하면 안 됩니다. 반대로 숫자형 데이터라고 해서 항상 수치형 데이터는 아닙니다. 등급 또는 학년 같은 값은 실제 숫자라기보다는 특정 범주를 나타내는 경우가 많습니다. 이 경우에는 원-핫 인코딩을 고려할 수 있습니다.

![원핫인코딩](./images/원핫인코딩.png)

In [ ]:
blood_map = {'A':0, 'B':1, 'AB':2, 'O':3}
df1_copy['blood_code'] = df1_copy['혈액형'].map(blood_map)  # 라벨인코딩
df1_copy.head()

    이름        소속사 성별       생년월일        키 혈액형    브랜드평판지수  성별2  성별3  blood_code
0  변우석   바로엔터테인먼트  남 1991-10-31  190.3cm   B  3,762,141    1    1         1.0
1  임영웅      물고기뮤직  남 1991-06-16  182.2cm   A  3,349,309    1    1         0.0
2  손흥민  로스앤젤레스 FC  남 1992-07-08    183cm  AB  3,067,512    1    1         2.0
3  박지훈   YY엔터테인먼트  남 1999-05-29    173cm  AB  2,831,201    1    1         2.0
4  유재석        안테나  남 1972-08-14    178cm   B  2,015,312    1    1         1.0

In [ ]:
pd.get_dummies(df1_copy['혈액형'])      # 원핫인코딩

        A     AB      B      O
0   False  False   True  False
1    True  False  False  False
2   False   True  False  False
3   False   True  False  False
4   False  False   True  False
5   False  False  False   True
6    True  False  False  False
7   False  False   True  False
8   False  False   True  False
9   False  False   True  False
10  False  False  False   True
11   True  False  False  False
12   True  False  False  False
13  False  False   True  False
14  False  False  False  False
15  False  False  False   True
16  False  False  False   True
17   True  False  False  False
18  False  False  False  False
19  False  False   True  False

In [ ]:
df1_copy = pd.get_dummies(df1_copy, columns=['blood'])       # 리스트에 여러 개를 넣으면 한번에 가능
df1_copy

KeyError: "None of [Index(['blood'], dtype='str')] are in the [columns]"

***
- AI 학습을 위한 데이터는 숫자형만 있어야 함(문자열은 이해를 못하니까)
    - 결측값도 없어야함
- 주석을 다 달아 놓고 복습한 후 코드를 싹 지우고 코드를 다시 작성해보면서 공부하는 것도 하나의 공부 방법
- 수업에서 언급한 내용들은 모두 필요한 내용들이므로 모두 숙지